# NumPy 

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy. To get started we need to install it!

## What are the advantages of NumPy over regular Python lists?

NumPy's arrays are more compact than Python lists -- a list of lists as you describe, in Python, would take at least 20 MB or so, while a NumPy 3D array with single-precision floats in the cells would fit in 4 MB. Access in reading and writing items is also faster with NumPy.

Maybe you don't care that much for just a million cells, but you definitely would for a billion cells -- neither approach would fit in a 32-bit architecture, but with 64-bit builds NumPy would get away with 4 GB or so, Python alone would need at least about 12 GB (lots of pointers which double in size) -- a much costlier piece of hardware!

The difference is mostly due to "indirectness" -- a Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16). A NumPy array is an array of uniform values -- single-precision numbers takes 4 bytes each, double-precision ones, 8 bytes. Less flexible, but you pay substantially for the flexibility of standard Python lists!

In [5]:
import numpy as np 


In [13]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [15]:
np.array(mylist)

array([1, 2, 3])

In [21]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [30]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [54]:
len(np.linspace(0,10))

50

In [58]:
np.linspace(0,20,5,dtype=int)

array([ 0,  5, 10, 15, 20])

In [60]:
np.linspace(0,10,dtype=int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [63]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [80]:
np.random.rand(5,5)

array([[0.2307165 , 0.5892573 , 0.18990855, 0.05402768, 0.01167826],
       [0.79633165, 0.05840226, 0.68055607, 0.29852293, 0.86403584],
       [0.51564086, 0.51786145, 0.23482474, 0.67373387, 0.44076785],
       [0.75137503, 0.87752025, 0.49009482, 0.18610545, 0.89596498],
       [0.38672122, 0.48376315, 0.49225017, 0.16866283, 0.85551238]])

In [74]:
np.random.rand(2,3)

array([[0.97533927, 0.41546327, 0.31673488],
       [0.12808216, 0.92269994, 0.24374535]])

In [84]:
np.random.seed(42)
np.random.rand(3,4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

### The main difference between numpy.random.rand() and numpy.random.randn() lies in the type of random distribution they generate:

## 1.random.rand():

Generates random numbers from a uniform distribution over the interval [0, 1).

This means the generated values are evenly spread between 0 and 1.
## 2.random.randn():

Generates random numbers from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1.

The values can be negative or positive and are more likely to be around 0, with fewer extreme values.

#### Key Differences:
rand() → Uniform distribution between 0 and 1.
randn() → Normal distribution with mean = 0, standard deviation = 1.
The two functions are used for different purposes depending on whether you need uniform or normally distributed random numbers!

## numpy.random.randint

The function numpy.random.randint() generates random integers. It returns a random integer (or an array of random integers) within a specified range.

In [97]:
np.random.randint(low, high=None, size=None, dtype=int)


In [91]:
np.random.randint(0,10)

5

In [93]:
np.random.randint(1,100,10)

array([ 2, 64, 60, 21, 33, 76, 58, 22, 89, 49])

In [101]:
#generating a 2D array matrix
np.random.randint(0,100,size=(3,4))

array([[90, 58, 41, 91],
       [59, 79, 14, 61],
       [61, 46, 61, 50]])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [104]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [106]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [115]:
arr= np.arange(25)
randarr = np.random.randint(0,50,10)

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [119]:
randarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [121]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [123]:
randarr.reshape(2,5)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [127]:
arr.max()

24

In [129]:
randarr.max()

39

In [131]:
arr.min()

0

In [133]:
randarr.min()

2

In [135]:
randarr.argmax()

7

In [137]:
randarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [140]:
arr.shape()

TypeError: 'tuple' object is not callable

In [142]:
arr.shape

(25,)

In [146]:
randarr.shape

(10,)

In [150]:
arr.reshape(1,25).shape

(1, 25)

In [152]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [154]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [156]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [159]:
arr.dtype

dtype('int32')

In [163]:
randarr.dtype

dtype('int32')

In [165]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')