# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [9]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [13]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [15]:
arr[8]

8

In [17]:
arr[-1]

10

In [19]:
arr[-2]

9

In [25]:
# Slicing using negative indices
print(arr[-3:])  # Elements from the 3rd last to the end: [30, 40, 50]
print(arr[:-2])  # All elements except the last 2: [10, 20, 30]


[ 8  9 10]
[0 1 2 3 4 5 6 7 8]


In [21]:
arr[-3:]

array([ 8,  9, 10])

In [23]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [31]:
arr[:4:-1]

array([10,  9,  8,  7,  6,  5])

In [35]:
arr[10:6:-1]

array([10,  9,  8,  7])

# Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [40]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
# Reset array, we'll see why I had to reset in  a moment

arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
#change slice
slice_of_arr[:]=999
slice_of_arr

array([999, 999, 999, 999, 999, 999])

In [64]:
slice_arr

999

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [79]:
arr_2d = np.array(([10,20,30],[40,50,60],[70,80,90]))
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [85]:
arr_2d[1]

array([[40, 50, 60],
       [70, 80, 90]])

In [87]:
arr_2d[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [89]:
arr_2d[0:2,1:]

array([[20, 30],
       [50, 60]])

In [93]:
arr_2d[1,1]

50

In [95]:
arr_2d[2][2]

90

In [97]:
arr_2d[2]

array([70, 80, 90])

In [99]:
arr_2d[2,:]

array([70, 80, 90])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src= 'numpy_indexing.png' width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

In [102]:
arr_2d[:,2]

array([30, 60, 90])

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [107]:
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
ar>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [111]:
ar<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [113]:
bool_arr = ar > 4

In [115]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [117]:
ar[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [119]:
ar[ar>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [123]:
x=5
ar[ar>x]

array([ 6,  7,  8,  9, 10])